### ISSUE TITLE
add show room pictures

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/iad#13]
![img_2356](https://cloud.githubusercontent.com/assets/72155/8192141/29c40db6-143a-11e5-870a-17ecec5c0f86.JPG)
![img_2353](https://cloud.githubusercontent.com/assets/72155/8192142/29d5dbe0-143a-11e5-9f70-0373e3116afc.JPG)
![img_2352](https://cloud.githubusercontent.com/assets/72155/8192144/29d943de-143a-11e5-8a9b-fb08c8502d50.JPG)
![img_2355](https://cloud.githubusercontent.com/assets/72155/8192143/29d75312-143a-11e5-831f-244b7313cf88.JPG)
![img_1252](https://cloud.githubusercontent.com/assets/72155/8192146/29db1c2c-143a-11e5-91d5-1050f9e41753.JPG)
![img_1255](https://cloud.githubusercontent.com/assets/72155/8192147/29dbbbe6-143a-11e5-9ea3-7010927c0c66.JPG)
![img_1256](https://cloud.githubusercontent.com/assets/72155/8192145/29dac984-143a-11e5-9a71-bf25271a36ca.JPG)

@radu88 if you can't edit the pictures, ask from Marie

**Comment by radu88** [comment]
You attached 7 pics, needed just 5. Picked 5 and put them in random order.

Let me know if it's ok
