### ISSUE TITLE
add navigation menu like this website

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/iad#5]
http://crtv.mk/e036w

**Comment by developergyan2015** [comment]
Just solved the menu issue please check once.

**Comment by bolom** [comment]
@developergyan2015 its working but not completely.
take a look. http://quick.as/PpZ6uB09V

**Comment by sergantonov** [comment]
Ok

2015-05-12 5:53 GMT+03:00 Bolo Michelin <notifications@github.com>:

**Comment by bolom** [comment]
@sergantonov thanks sergey but we are working with our regular developer we didn't need you anymore

**Comment by sergantonov** [comment]
All right! Why did you send me a message on my e-mail?
Can you change the feedback in odesk to 5 stars instead of 3.95 due this is
my first project in oDeck? Thanks.

2015-05-12 12:44 GMT+03:00 Bolo Michelin <notifications@github.com>:

**Comment by bolom** [comment]
@sergantonov i didn't seen you anything. You have to stop follow this repo.

**Comment by bolom** [comment]
@developergyan2015 it's not working

**Comment by sergantonov** [comment]
Ok.Thank you very much!

2015-05-12 13:08 GMT+03:00 Bolo Michelin <notifications@github.com>:

**Comment by bolom** [comment]
stop to reply here

2015-05-12 6:13 GMT-04:00 sergantonov <notifications@github.com>:

**Comment by developergyan2015** [comment]
@bolom this issues solved. Please have a look.

**Comment by bolom** [comment]
http://quick.as/8z40F6xB4

**Comment by bolom** [comment]
@developergyan2015  still not working  :( http://jonathannicol.com/blog/2011/08/06/build-a-parallax-scrolling-website-interface-with-jquery-and-css/

**Comment by developergyan2015** [comment]
@bolom  menu is working fine but the sticky menu that I added making some problem here so I am going to remove that sticky feature will that fine? After that everything will be fine.

**Comment by bolom** [comment]
yes

2015-05-13 22:04 GMT-04:00 developergyan2015 <notifications@github.com>:
