### ISSUE TITLE
replace the picture for the home slider

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/iad#9]
![capture d ecran 7](https://cloud.githubusercontent.com/assets/72155/8086120/c3e8ee1c-0f61-11e5-9808-61d063a6acdd.png)
![slider_01](https://cloud.githubusercontent.com/assets/72155/8086044/69512a82-0f61-11e5-89e0-236908d9fedb.png)
![slider_02](https://cloud.githubusercontent.com/assets/72155/8086045/69514c1a-0f61-11e5-94a2-cd1de8b2678d.png)
![slider_03](https://cloud.githubusercontent.com/assets/72155/8086046/6951d8b0-0f61-11e5-9011-33980fd5f10d.png)

**Comment by bolom** [comment]
@radu88 it's too small. the imag should take all space on the slide like here

http://shopsincerelyjules.com/

http://lordalexworks.github.io/iad/

**Comment by radu88** [comment]
The updated image has exactly the same size as the previous one. The only difference is that in the old sofa picture, there was no background of the sofa, so it would blend in perfectly. 

Have a look at the old slider - http://lordalexworks.github.io/iad/img/banner1-old.png - Image size is 951x277px
Have a look at the new slider - http://lordalexworks.github.io/iad/img/banner1-old.png - Image size is 951x277px - just like the original one.

Do you want me to go ahead and increase the size of the slider to be bigger ?

**Comment by bolom** [comment]
i have added my comment in the wrong issue

**Comment by bolom** [comment]
@radu88 yes can u try ?

**Comment by bolom** [comment]
@radu88 we can add our designer to increase the size. what's is more simple for you ?

**Comment by radu88** [comment]
The original pictures of the slider are in that format, so I dont want to increase it in photoshop as it will damage the quality of it. Please provide images at a higher resolution and I will try and sort it out.

**Comment by bolom** [comment]
@radu88 can u give me size ?. I will ask

**Comment by radu88** [comment]
Dont have a standard size, maybe 1920x1080 ? And if I need them smaller, I will edit them.

**Comment by bolom** [comment]
ok

2015-06-12 20:26 GMT-04:00 radu88 <notifications@github.com>:

**Comment by bolom** [comment]
the new pictures

https://basecamp.com/1759169/projects/8034129/messages/43585049?enlarge=160845408#attachment_160845408

**Comment by bolom** [comment]
https://www.evernote.com/l/AGBtIzNdL7pBeKTFno88Q-ndR4X-t2Twogo
